"""Descripción de la revision

Revision ID: aa12ee8d31d0
Revises: c21f89885bda
Create Date: 2026-02-18 18:26:23.574419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa12ee8d31d0'
down_revision: Union[str, Sequence[str], None] = 'c21f89885bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('ultimo_visita', sa.DateTime(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_prim', sa.Integer(), nullable=True),
    sa.Column('cod_sec', sa.String(length=10), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('valor_int', sa.Integer(), nullable=True),
    sa.Column('valor_dec', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('valor_str', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('ident_fiscal', sa.String(length=15), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=False),
    sa.Column('moneda_base', sa.String(length=10), nullable=False),
    sa.Column('zona_horaria', sa.String(length=10), nullable=False),
    sa.Column('is_alert_inventar_bajo', sa.Boolean(), nullable=True),
    sa.Column('is_modo_offline', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('sucursal', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('proveedor', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('codigo_documento', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('notas_adicionales', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('IGV', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('total', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=15), nullable=False),
    sa.Column('costo', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('precio_venta', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=50), nullable=True),
    sa.Column('tipo_documento', sa.String(length=10), nullable=False),
    sa.Column('codigo_documento', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('IGV', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('total', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('notas_adicionales', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos_productos',
    sa.Column('ingreso_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('ingreso_id', 'producto_id')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cantidad_anterior', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id', 'producto_id')
    )
    op.create_table('ventas_productos',
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('subtotal', sa.Float(precision=10, asdecimal=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('venta_id', 'producto_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas_productos')
    op.drop_table('stocks')
    op.drop_table('movimientos')
    op.drop_table('ingresos_productos')
    op.drop_table('ventas')
    op.drop_table('productos')
    op.drop_table('ingresos')
    op.drop_table('usuarios')
    op.drop_table('empresa')
    op.drop_table('configuracion')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
