"""add variables


Revision ID: d0650449259d
Revises: aa12ee8d31d0
Create Date: 2026-02-20 09:23:03.005270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0650449259d'
down_revision: Union[str, Sequence[str], None] = 'aa12ee8d31d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True))
    op.add_column('clientes', sa.Column('direccion', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'direccion')
    op.drop_column('clientes', 'fecha_nacimiento')
    # ### end Alembic commands ###
